#!perl

# DATE
# VERSION

use 5.010001;
use strict;
use warnings;

use Benchmark::Dumb qw(cmpthese);
use FindBin '$Bin';
use lib "$Bin/../lib";

use Time::Duration::Parse ();
use Time::Duration::Parse::AsHash ();

cmpthese(
    0,
    {
        'TDP  <>'     => sub { Time::Duration::Parse::parse_duration        ('') },
        'TDPA <>'     => sub { Time::Duration::Parse::AsHash::parse_duration('') },
        'TDP  <3h>'   => sub { Time::Duration::Parse::parse_duration        ('3 hours') },
        'TDPA <3h>'   => sub { Time::Duration::Parse::AsHash::parse_duration('3 hours') },
        'TDP  <3h4m>' => sub { Time::Duration::Parse::parse_duration        ('3 hours 4 minutes') },
        'TDPA <3h4m>' => sub { Time::Duration::Parse::AsHash::parse_duration('3 hours 4 minutes') },
    },
);
